package: locked
version: '0.0.1'
author: 'Thomas Skerbis'
supportpage: https://github.com/skerbis/locked
requires:
    packages:
        structure/content: '^2.1.0'
    redaxo: '^5.12.0-dev'
    php:
        version: '>=7, <9'
conflicts:
    packages:
        accessdenied: '>0.0.0'
