package: locked
version: '1.0.0-dev'
author: 'Thomad Skerbis'
supportpage: https://github.com/KLXM/locked
requires:
    packages:
        structure/content: '^2.1.0'
    redaxo: '^5.10.0'
    php:
        version: '>=7.4, <9'
conflicts:
    packages:
        accessdenied: '>0.0.0'
